language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install --upgrade pip"
  - "pip install wheel"
  - "pip wheel ."
  - "pip install ."
# command to run tests
script:
  - pylnker.py
